### ISSUE TITLE
Not working on Edge

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#1534]
The script stopped working a few days ago.

Microsoft Edge 41.16299.15.0
Tampermonkey 4.5.5570

Log error:

Execution of script '4chan X' failed! 'BroadcastChannel' is not defined

ReferenceError: 'BroadcastChannel' is not defined
at Anonymous function (Function code:4985:5)
at Anonymous function (Function code:4425:1)
at tms_deaf0ee0_acd9_4034_bc49_9ab0869f12f0 (Function code:146:2)
at Anonymous function (Unknown script code:2:375)
at Anonymous function (Function code:2:1)
at Anonymous function (Function code:1:58)
at Function code (Function code:1:5)
at Anonymous function (Unknown script code:2:375)
at N.E_c (Unknown script code:3:193)
at da (Function code:60:49)`

![applicationframehost_2017-10-17_17-40-44](https://user-images.githubusercontent.com/11687827/31688302-bb2d0c0e-b36a-11e7-8f6b-702f7f3db4cb.png)

**Comment by ccd0** [comment]
Thanks for reporting. This should be fixed now.

**Comment by mariojuniorjp** [comment]
You're welcome, but still now working. Now I don't get any error messages in the log, but still not working.

**Comment by ccd0** [comment]
Those messages are normal. Can you try sticking `console.log` statements into `Main.init` to find out where the execution halts?

**Comment by ccd0** [comment]
If you need it working right away, try an older version of Tampermonkey. (If any older version of 4chan X works with the current Tampermonkey, that would also be useful to know.)

**Comment by mariojuniorjp** [comment]
Is very strange because console.log don't have any message about error or something. I do not know if I have an older version of tampermonkey installed on the Edge, but I'll test it.

**Comment by derjanb** [comment]
FYI:

Microsoft Edge 41.16299.15.0
Tampermonkey 4.5.5570
4chan X 1.13.13.1

is working fine here.

**Comment by derjanb** [comment]
FYI:

4chan X 1.13.13.1
Microsoft Edge 41.16299.15.0
Tampermonkey 4.5.5570

is working fine here as far as I can tell.

**Comment by ccd0** [comment]
@mariojuniorjp
Are you sure you have everything up to date? What versions of everything are you running? Have you tried temporarily disabling other extensions to check for a conflict?

**Comment by mariojuniorjp** [comment]
@ccd0 @derjanb 

Yep, I'm sure. Still not working for me.

![applicationframehost_2017-10-23_13-34-08](https://user-images.githubusercontent.com/11687827/31901118-51271964-b7ff-11e7-9a6b-22b7317df653.png)
![applicationframehost_2017-10-23_13-34-20](https://user-images.githubusercontent.com/11687827/31901119-51438de2-b7ff-11e7-9cfa-8f662d65888b.png)

The only extensions installed are Tampermonkey and uBlock Origin. Even uninstalling uBlock will not work.

**Comment by IamYazen** [comment]
```
4chan-x             =  v1.13.13.2
Edge                  =  41.16299.15.0
Tampermonkey = v4.5.5570
```

Not getting any errors, however, the script is not working for me.

**Comment by twisted11** [comment]
I have the same issue with:
Microsoft Edge 41.16299.15.0
4chan X 1.13.13.2
Tampermonkey v4.5.5570

Here's the error I get:

```
ERROR:

 Execution of script '4chan X' failed! Invalid procedure call or argument

 TypeError: Invalid procedure call or argument
   at Anonymous function (Function code:24648:11)
   at $.getSync (Function code:5237:7)
   at Main.init (Function code:24645:7)
   at Anonymous function (Function code:25107:1)
   at tms_590a960f_d266_4e90_a85e_6075db2ef2b1 (Function code:147:2)
   at Anonymous function (Unknown script code:2:375)
   at Anonymous function (Function code:2:1)
   at Anonymous function (Function code:1:58)
   at Function code (Function code:1:5)
   at Anonymous function (Unknown script code:2:375)

 CSP14312: Resource violated directive ‘script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'’ in meta http-equiv="Content-Security-Policy">: http://utraffic.engine.adglare.net/?710227704. Resource will be blocked.

2 CSP14312: Resource violated directive ‘script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'’ in meta http-equiv="Content-Security-Policy">: http://www.google-analytics.com/analytics.js. Resource will be blocked.

```

**Comment by mariojuniorjp** [comment]
Still not working.

**Comment by mariojuniorjp** [comment]
And still not working.

Microsoft Edge 42.17133.1.0
Tampermonkey 4.6.57.57
