### ISSUE TITLE
Broken and "Failed to load board configuration. Connection Error"

### ISSUE THREAD

**Issue by ProfessorInternet** [ccd0/4chan-x#1746]
Hi, today when I tried to load any thread from any board or the main site everything is broken and white and I get this message at the top of the page "Failed to load board configuration. Connection Error"

Now I tried some fixes and none of them worked so I tried uninstalling whatever ad blocker I had, greasemonkey and same thing

Okay then that was on firefox so I tried with just the internet explorer, same thing

So I want to know what is this? Is this some new kind of ramsomware malware virus thing? Don't be fooled by my nickname I actually have no idea how internet works

**Comment by ccd0** [comment]
What happens if you try to visit https://a.4cdn.org/boards.json directly?

**Comment by ProfessorInternet** [comment]
It shows this https://imgur.com/a/45A66 Is that how is it supposed to work?

btw Merry Christmas!

**Comment by ccd0** [comment]
Yes, that's how it should look. Are you still getting the message? This could just be a connection error, like the message said.

Merry Christmas to you too!

**Comment by ccd0** [comment]
If you're still having the problem, try temporarily disabling all other extensions and userscripts so if you can see if one of them is causing a conflict.

**Comment by ProfessorInternet** [comment]
Yes I am still getting it, I only have adblocker ultimate tried disabling it and nope same thing.

**Comment by ccd0** [comment]
What version of Firefox? What userscript manager and what version?

Does it happen in a fresh profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by ProfessorInternet** [comment]
Yes it also happened on a new profile 

Firefox quantum 57.0.2
Greasemonkey 4.1

**Comment by impman** [comment]
This is also occurring to me, with auto-update broken as well. Tested on a new profile with zero other addons or userscripts, still occurs. Tried both Greasemonkey and Violentmonkey (in isolation), both give the same issues.

Firefox 57.0.2
Greasemonkey 4.1
Violentmonkey 2.8.23

**Comment by vandr0iy** [comment]
idem for me
Firefox 57.0.4
Greasemonkey 4.1

**Comment by ProfessorInternet** [comment]
You guys tried browsing without 4chanX? Because even the auto-updater doesn't work for me. I mean it doesn't update.

Also when I press f12 and go to the console I get these messages
Loading failed for the <script> with source “https://utraffic.engine.adglare.net/?653284199”.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/a/threads.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/a/thread/166999150.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by AnonymousRequestee** [comment]
Having same problem. "Failed to load board configuration. Connection error." will pop up, and in console it will throw CORS errors.

```
"4chan X failed to load: https://a.4cdn.org/his/threads.json"  4chan-X-beta.user.js:4534:20

"4chan X failed to load: https://a.4cdn.org/his/thread/3972307.json" 4chan-X-beta.user.js:4534:20

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/his/thread/3972307.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Firefox 56.0.2
Greasemonkey 3.17

Entering the JSON URLs directly loads them fine.

**Comment by ProfessorInternet** [comment]
Well guys at least I'm glad we're all in this together

Group hug

**Comment by builderheg** [comment]
Is the native extension also broken for you guys? I have this problem too, and not even the native extension is working properly. I'm on Firefox 57.0.4 with Violentmonkey

**Comment by AnonymousRequestee** [comment]
Native extension also throws the same error. A lot more of its functionality appears to work but if you open the console you'll notice the same CORS errors popping up whenever a thread attempts to auto-update, as well as a few others.

Example:
```
ThreadStats: couldn't get the catalog (0)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/his/threads.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
OPTIONS XHR https://a.4cdn.org/his/thread/3998651.json [HTTP/2.0 503 Service Unavailable 20ms]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/his/thread/3998651.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Using a browser extension, I was actually able to manually alter the response headers to include `Access-Control-Allow-Origin https://boards.4chan.org` but it didn't matter, even after doing that I just got the same error (Cross-Origin Request Blocked) with a different Reason, CORS Preflight Channel Failed.

I noticed that a few times since this started happening, a "browser integrity check" page has popped up on the site, one of those CloudFlare things basically to make sure you're not a bot, maybe this bug has something to do with a recent CloudFlare change?

**Comment by impman** [comment]
Yes, native extension also does not autoupdate. CSS is broken on page listing unless you open an image to trigger the CloudFlare bot checker, after which CSS will work, but autoupdate still will not.

**Comment by deadman3000** [comment]
Anyone got a fix apart from rolling back to an earlier version?

**Comment by asdasdasdasd27** [comment]
Same problem here, I've had it for a month I think. CSS is broken until I open an image but the autoupdate is broken forever like impman said. I can browse 4chan normally but I have to refresh the page to update. This problem ONLY happens if I use my house's wifi and everything works normal if I share internet from my phone to my PC which is weird. 
This is beyond 4chan X though since it also happens in the native extension AND the mobile app Clover, it's happening on our end. I hope it doesn't hurt anybody if we discuss it here to find a solution. I also had uMatrix but removing it did nothing.

**Comment by ProfessorInternet** [comment]
uMatrix didn't work for me either

Maybe it's time to say goodbye to 4chan after all

**Comment by builderheg** [comment]
It works for me now, for some reason. I still get this error:
`Content Security Policy: The page’s settings blocked the loading of a resource at https://www.google-analytics.com/analytics.js (“script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://boards.4chan.org 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com”).`

But it doesn't seem to affect anything. And this happened on its own, overnight, so I'm not sure what changed. Is it working for anyone else now?

**Comment by ProfessorInternet** [comment]
No

;_;

**Comment by AnonymousRequestee** [comment]
If CSS, images etc. to be broken for you, type 4cdn.org into the URL bar and visit it directly. CloudFlare wants to make sure you're not a bot for some reason and only actually gives your browser the test if you visit that domain directly. Once it makes sure you're not a bot, go back and reload whatever page was broken, and assets from 4cdn.org should load... Unless they're the .json files which are the subject of this issue, in which case they still fail to load because of the Cross-Origin Request error. But at least the site returns to being only half-broken.

**Comment by builderheg** [comment]
Aaand it's broken again. It just randomly broke out of nowhere, just like last time. It was nice having it work while it lasted.

Before the problem briefly fixed itself, I did report the it through 4chan's feedback form, but it looks like that form hasn't been used in years so I didn't really place any hope in it. That's really the only idea I have left, to try to contact a 4chan dev or something.

**Comment by ccd0** [comment]
@builderheg
Did you try what @AnonymousRequestee suggested?
What happens if you visit these?
https://a.4cdn.org/ping.js
https://s.4cdn.org/ping.js
https://sys.4chan.org/ping.js

**Comment by builderheg** [comment]
Yeah, the CSS broke right away and visiting 4cdn.org fixed it, but that's the only thing it fixed.

Visiting those links gives just gives me pages that say, "fourchan_up('api');", "fourchan_up('static');
", and "fourchan_up('sys');", is that what I'm supposed to see?

**Comment by ccd0** [comment]
Yes. What errors are you getting right now?
Does visiting
https://a.4cdn.org/boards.json
give you the expected results?

**Comment by builderheg** [comment]
In a thread, I'm getting a board configuration error, and in the console, this:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/k/thread/36622848.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
4chan X failed to load: https://a.4cdn.org/k/thread/36622848.json`

I also get this on the index: `Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.`

Also on the index, with JSON index turned off in settings:
 `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/co/threads.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Content Security Policy: The page’s settings blocked the loading of a resource at https://www.google-analytics.com/analytics.js (“script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://boards.4chan.org 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com”).
`

Visiting the link shows the same thing as what's in the screencap from OP, so that looks right.

**Comment by ccd0** [comment]
Can you try this?
1. clear your cache
2. open https://boards.4chan.org/k/thread/36622848
3. open dev tools (F12)
4. go to console tab and paste
`x=new XMLHttpRequest(); x.open('GET','https://a.4cdn.org/k/thread/36622848.json'); x.send();`
5. go to network tab, select 36622848.json entry and headers tab on right
6. maximize and screenshot

**Comment by builderheg** [comment]
https://i.imgur.com/Mt7BebQ.png

**Comment by deadman3000** [comment]
Is there any way to get rid of the brown box saying 'image corrupted' when I drag it into the reply box?

**Comment by builderheg** [comment]
I just flushed my dns with the command prompt, restarted Firefox, and it's working again (temporarily, at least).

**Comment by VallardX** [comment]
Same error, but when I open the link in the first reply https://a.4cdn.org/boards.json 

I get this instead:
![image](https://user-images.githubusercontent.com/3863005/36057758-e8c3bd54-0df9-11e8-8e31-d48b94bb3270.png)
which sees to be different of what other people are getting

And this one as well: 
Error fetching archive data from
https://mayhemydg.github.io/archives.json/archives.json
Connection Error

**Comment by asdasdasdasd27** [comment]
Flushing my dns doesn't work for me sadly, might be different broken things

**Comment by builderheg** [comment]
Or they really are the same, because now flushing my dns doesn't work. I'm giving up.

**Comment by ccd0** [comment]
https://support.cloudflare.com/hc/en-us/articles/200171896-Why-am-I-getting-a-503-Service-Temporarily-Unavailable-error-message-

> A 503 Service Unavailable message with no cloudflare in the message means you need to contact your hosting provider for assistance (it generally means your host is rate limiting requests to your site). On the other hand, a 503 Service Temporarily Unavailable error message with "cloudflare" in it means you are hitting a connection limit in a Cloudflare datacenter.

So to get this looked into, you'd need to repeat https://github.com/ccd0/4chan-x/issues/1746#issuecomment-361133820 and also take a screenshot of the "Response" tab, also changing the now dead thread to https://boards.4chan.org/k/thread/23385784 and sending the results to https://www.4chan.org/feedback, because this is clearly a problem on 4chan's or Cloudflare's end.

1. clear your cache
2. open https://boards.4chan.org/k/thread/23385784
3. open dev tools (F12)
4. go to console tab and paste
`x=new XMLHttpRequest(); x.open('GET','https://a.4cdn.org/k/thread/23385784.json'); x.send();`
5. go to network tab, select 23385784.json entry
6. select headers tab on right
7. maximize and screenshot
8. select response tab
9. screenshot again
10. send to https://www.4chan.org/feedback (you can post it here too, but I'm not going to be able to do much about it)

**Comment by ccd0** [comment]
@deadman3000
see https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#error-reading-metadata

**Comment by ccd0** [comment]
nonijod, https://github.com/ccd0/4chan-x/issues/1834#issue-297587717:

Recently Hiro upped the protection level in Cloudflare setting. As a result if CF thinks you're suspicious (for example by having updater with low timeout), it marks your IP and requires you to periodically see the "Checking your browser" page, which also drops a cf_clearance cookie that is then used with each request.
First annoyance is that, as people don't really have a reason to type in 4cdn.org, they won't see this page and won't know why isn't anything loading. All that has to be done in this situation is to open for example an image in new tab.
Second and the most significant annoyance is that anything requested via XHR, such as thread updater or JSON index stops working as it doesn't send the cookie with the request, to which CF responds with 503.
Non-XHR requests such as expand image work fine.

Firefox 52.6.0 ESR
Greasemonkey 3.17

**Comment by ccd0** [comment]
anonymau5, https://github.com/ccd0/4chan-x/issues/1834#issuecomment-366079038:

Ok, I fixed it. First I disabled umatrix and 4chanx and refreshed. Then I renabled 4chanx and refreshed. Then I renabled umatrix and refreshed. It broke. I enabled cookies for 4cdn.org and that made it work again.

No idea if this is going to be a long term fix but we'll see.

**Comment by ccd0** [comment]
nonijod, https://github.com/ccd0/4chan-x/issues/1834#issuecomment-366093223

No cookies being blocked or nuked here.

**Comment by ccd0** [comment]
desuwa says in https://github.com/4chan/4chan-API/issues/57#issuecomment-366303426:

This will be fixed soon.

Please email your IP to api@4chan.org so I can unban it.

**Comment by asdasdasdasd27** [comment]
Back to normal for me. Don't forget you are here forever.jpg

**Comment by DocHobo** [comment]
So this is just something we have to wait for 4chan to fix on their end?  It shouldn't be tied to my IP because chrome works fine, but I get the "Failed to load board configuration. Connection Error" "Index refresh failed. Connection Error" stuff on firefox

**Comment by riesza** [comment]
Try clearing your cache, cycling your IP if dynamic, flushing DNS etc. It was already fixed for me yesterday, not that long after desuwa's comment.

**Comment by nonijod** [comment]
With another IP everything works well, however my home IP is static so that isn't the way. It isn't the browser as iexplore and Clover are broken too because of this.

**Comment by riesza** [comment]
Just had it break again until I cycled my IP. Weird stuff

**Comment by hamwich15** [comment]
Same thing is happening to me, is Firefox the problem?

**Comment by riesza** [comment]
No, I have it in Chromium, too. It feels like it's something IP-based. It breaks, I cycle my IP and it works again for like one and a half hours and then it breaks again.

**Comment by ccd0** [comment]
If this continues to be a problem we can try setting `withCredentials` on every request which should solve this part:
> Second and the most significant annoyance is that anything requested via XHR, such as thread updater or JSON index stops working as it doesn't send the cookie with the request, to which CF responds with 503.

**Comment by ccd0** [comment]
If you're having this problem, let me know if the most recent beta version (v1.14.0.8) helps. You will still need to open an image in a new tab at least once to trigger the bot checker.

**Comment by ccd0** [comment]
Never mind, v1.14.0.8 seems to have broken requests for everyone on Firefox. Reverting.

**Comment by ProfessorInternet** [comment]
Well either he fixed it, or 4chanx fixed it, or it fixed itself or I fixed it but the bottom line is it is fixed, I can view the mainboard, I can post, I can view pics, the captcha works, everything works

Oh man I'm so happy I thought I would never browse 4chan again and I would have to get a job and a wife or something I'm sure thish high will end in a day or less but until then

I hope this never happens again and that everybody's problems get solved out too

**Comment by lc-guy** [comment]
Yeah no, nothing at all fixed for me. Still can't access catalog or refresh in threads, even with the native extension.

**Comment by xXFoXbAgXx** [comment]
Still completely broken for me, no catalog or refreshing threads

**Comment by unknown--** [comment]
A temporary fix is to obtain an new IP and limit your thread updater to 20 seconds. You might need to increase it even more if you tend to have many threads open.

**Comment by xXFoXbAgXx** [comment]
Doesn't actually fix anything for me, still have a connection error on the thread updater with it set at 65 seconds, plus the catalog still not working

**Comment by unknown--** [comment]
Even with a new IP?

**Comment by xXFoXbAgXx** [comment]
yeah, I'm forced to reload the whole page to update threads now at this point, and catalog only works if i turn off 4chan X

**Comment by xXFoXbAgXx** [comment]
Hmm, it works fine if i use mobile data however

**Comment by riesza** [comment]
Yeah it's definitely some IP shit. I can't even phonepost until I cycle my IP. I wouldn't be surprised if Hiro found a way to soft ban people who send too many refresh requests in a given time.

**Comment by xXFoXbAgXx** [comment]
It's gotta be more than that, because as soon as i disable 4chan X, everything works like normal

**Comment by unknown--** [comment]
Because 4chan-x makes API requests which are denied if your IP is banned. It's different if you use the native catalog/site.

**Comment by xXFoXbAgXx** [comment]
oh well, I'm not exactly good with code to be frank, any possible time frame when this will be fixed, if it even can be?

**Comment by abbacus86** [comment]
Same issue, used aggressive updating of every 5 seconds for years prior to this. I have to manually refresh pages for updates, still using static IP and haven't tried rotating. Chrome and Firefox both have this issue, No images load and broken CSS until I manually open an img link and am subjected to cloudflare bot detection (multiple times a day it seems). Surprised there aren't more people presenting with this issue.

**Comment by Teapsalm** [comment]
I'm having the same issue. Always keep 4chanx updated. Disabling 4chan x and OneeChan both seem to leave the site not functioning properly for me, so I have to assume there's something wrong on the site's end.

**Comment by randoomdude** [comment]
It's hillarious because for a brief second you can see the site load the threads normally, then they all disappear, so close yet so far.
https://a.doko.moe/pnabtu.webm

**Comment by randoomdude** [comment]
Alright, seems to be fixed if I get rid of the violent monkey script and just install it through chrome extension, using version 1.13.15.9 from the store, I tried installing from the site but chrome said it was corrupt and wouldn't run it.

**Comment by whoknows22** [comment]
It seems to have fixed itself for me, although that might be because I spent most of today without any threads open so there was no auto-refreshing going on.

**Comment by DocHobo** [comment]
yeah it's working fine for me on firefox now, who knows for how long though

**Comment by muffled357** [comment]
Finally started working for my out of the blue. Hopefully it stays that way.

**Comment by impman** [comment]
Only works on Wi-Fi for me, which probably means I have to cycle the router.

**Comment by asdasdasdasd27** [comment]
Fixed for me too. Thanks ccd0 for helping even though it wasn't 4chan X.

**Comment by AnonymousRequestee** [comment]
@ccd0 
It seems as though this issue has returned. I'm getting 503 and CORS errors again when using 4chan X, but opening the .json URLs directly loads them just fine. CSS is also broken until I visit 4cdn.org directly and it checks my browser.

When trying to load the catalog:
```
GET XHR https://a.4cdn.org/g/threads.json [HTTP/2.0 503 Service Unavailable 43ms]
"4chan X failed to load: https://a.4cdn.org/g/threads.json"
```

When trying to load a thread:
```
GET XHR https://a.4cdn.org/g/thread/65634180.json [HTTP/2.0 503 Service Unavailable 32ms]
"4chan X failed to load: https://a.4cdn.org/g/thread/65634180.json"  4chan-X-beta.user.js:4545:20
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/g/thread/65634180.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by AnonymousRequestee** [comment]
Never mind, desuwa explained the problem. Turns out having the thread updater set to 1 second can potentially cause problems related to sending too many requests. Once I set it to ten seconds the issue went away a few hours later. Just writing this in case anyone else has the same problem in the future.

**Comment by mraper3** [comment]
Trying to set the thread updater time, but the CSS is so broken it doesn't even show it.  What can I do?


![no thread updater_](https://user-images.githubusercontent.com/5323781/39217374-553a086a-47e5-11e8-8d89-019a0be494fc.jpg)
