### ISSUE TITLE
404 redirection stopped working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1811]
404 redirection stopped working today. I am using version 1.14.06 since it came out.
I get redirected to the 4chan 404 page and at the top of the page it says "404.html0100777000000000000000000002114313237077334007223 0ustar00"

**Comment by ccd0** [comment]
Thanks for reporting. v1.13.15.9 / 1.14.0.7 should fix this.

**Comment by esgwpl** [comment]
It's still happening for me, on both v1.13.15.9 and 1.14.0.7
I'm using 27.7.1 Pale Moon and 3.31beta1 [Greasemonkey](https://github.com/janekptacijarabaci/greasemonkey/)
Here's the thread I'm trying to open: https://boards.4chan.org/tv/thread/94423978

**Comment by CptWinters** [comment]
Having the same issue as well on version 1.13.15.9.

I'm using Firefox 58.0.2 64bit with Greasemonkey 4.2

**Comment by dumpsters** [comment]
Also happening to me on Firefox 58.0.2 with ViolentMonkey

**Comment by dlfsjdfjodifjsodifjsdo** [comment]
same here on 1.13.15.9 with tampermonkey on firefox 59

**Comment by esgwpl** [comment]
Seems to be working now on 1.14.0.10

**Comment by ccd0** [comment]
4chan was adding some garbage to the beginning of the 404 page that made it not valid HTML. I'm not seeing it anymore, so it's probably fixed on their end.
