### ISSUE TITLE
Quote hover + unread line cause lag due to style recalculation

### ISSUE THREAD

**Issue by bakugo** [ccd0/4chan-x#2214]
When a thread updates, the unread line, if hidden, is [re-inserted](https://github.com/ccd0/4chan-x/blob/0ca735c200da969026bcc94c1e94a5452c04c390/src/Monitoring/Unread.coffee#L203). This causes a full style recalculation, which can freeze the page for upwards of 200ms in large (700+ post) threads (this is on a good CPU, on a toaster it would probably be much worse). Happens on both Chrome and Firefox.

This isn't really a big deal on its own, but ever since commit https://github.com/ccd0/4chan-x/commit/0ca735c200da969026bcc94c1e94a5452c04c390, the unread line is now updated on the `PostsInserted` event instead of `ThreadUpdate`, and this new event is fired when a quote is hovered. This means that the page will lag/freeze every time a quote is hovered, if the unread line is currently hidden.

**Comment by ccd0** [comment]
Shouldn't this only happen when the unread line is at the end of the thread? It would probably be more efficient to remove the line rather than hiding it, but I'm not sure how to replicate the page freeze behavior.

**Comment by bakugo** [comment]
It only happens when the unread line is at the bottom/hidden, yes.
How to reproduce (works on a clean install with no settings changed):

* Find a large thread ([archived /vg/ threads](https://boards.4channel.org/vg/archive) work well)
* Scroll to bottom
* Refresh the page
* Hover over any quotelink while moving the cursor

[Looks like this](https://files.catbox.moe/rmgbgs.webm)

Also affects embed links with hover previews like youtube videos.

**Comment by ccd0** [comment]
>Also affects embed links with hover previews like youtube videos.

Are you sure this has anything to do with the unread line? That shouldn't fire `PostsInserted`. Have you tested with the unread line turned off?

**Comment by ccd0** [comment]
Alright, I think the quote preview issue is fixed. Do you know if the issue with video hover previews happened in older versions?

**Comment by bakugo** [comment]
You're right, the lag when hovering over video previews is a different issue.
Apparently a reflow is being triggered by reading `document.documentElement.clientHeight` [here](https://github.com/ccd0/4chan-x/blob/ed01e4ca5f3a909a07a818799220368c41eb678d/src/General/UI.coffee#L320).

**Comment by bakugo** [comment]
Inserting the embed preview element into `Header.hover`/`hoverUI` instead of directly into the body [here](https://github.com/ccd0/4chan-x/blob/d4cd42ddfcdfc77cb7dcc043d51ec741ded65707/src/Linkification/Embedding.coffee#L134) (making it behave like all the other hovers) seems to avoid this issue, but I don't know if ihavenoface did that intentionally or not.

**Comment by ccd0** [comment]
`Header.hover` was from Zixaphir 5833ad4fdaf91bb9e2606a771f0776356a8ebef1 and was never in Mayhem or ihavenoface's branches. I should have changed it to that when I merged it, but I overlooked it.

**Comment by shadow7483147** [comment]
Seems like this is still a problem, but I don't know how to investigate it. Here's a profiler snapshot of me just hovering over a quote link. (Chromium)

https://drive.google.com/file/d/14XyYCgfnO1rzAFH0b-1VGlRWu-wKtoH0/view?usp=sharing
