### ISSUE TITLE
arch.b4k /v/ archive file redirection 

### ISSUE THREAD

**Issue by handpain** [ccd0/4chan-x#2409]
The aforementioned archive now keeps full images again, so could you enable that as the file redirect option in the 4chanX archive options for /v/? Thanks

**Comment by ccd0** [comment]
Done.
For future reference, issues about the archive list should go to https://github.com/MayhemYDG/archives.json

**Comment by 1sad** [comment]
uh, so its still broken?.. i tried to add lines like it says, even save them to a file and try to link the file in that box, how do i fix it? archive is pretty much useless on /v/ right now for files and you have to manually link files and search for them, and if you had an image link open and it 404 youre just fucked
![archive](https://user-images.githubusercontent.com/23120024/67161674-6730ab00-f365-11e9-9abe-b6b5c6724fe6.PNG)

**Comment by ccd0** [comment]
https://arch.b4k.co/meta/thread/247/#254

**Comment by 1sad** [comment]
ah, well shit... 
thanks

posting pic of post for the sake of whoever might be looking at this in the future
![image](https://user-images.githubusercontent.com/23120024/67233945-d503d200-f44c-11e9-8d6d-8cda35570748.png)
