### ISSUE TITLE
"Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error"

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2520]
Submitter: Chris R Jackson
Email: DeltaD36@gmail.com
All threads and posts inside said threads seem to be being hidden automatically and I am getting the report title error.

**Comment by DeltaD36** [comment]
I also recently installed Privacy badger last week, but this problem didn't start happening until yesterday.
Also I've been trying to play AI Dungeon 2 and using the Collab version that seems to download something from GitHub as well but I have no idea if that is connected, but it did start around that time yesterday when I was attempting to use it.

**Comment by ParrotParrot** [comment]
Due to a github username change, the archive.json repository has stopped working
It's still there, just hasn't been updated to reflect the name change as of yet and so it still points to the old URL. You can get it now at
https://nstepien.github.io/archives.json/archives.json
and update it directly in the script yourself

**Comment by swablueme** [comment]
Very nice, thankyou @ParrotParrot

**Comment by nouse1234** [comment]
Worked for me as well.
I changed line 484 to
 archiveLists: 'https://nstepien.github.io/archives.json/archives.json',

I also exchanged line 79 to
// @connect      netstepien.github.io (replacing mayhemydg).

Was the second step necessary?

**Comment by g-2-s** [comment]
Didn't work for me, I still get the error message.

**Comment by voronalis** [comment]
Didn't work for me either.

**Comment by ccd0** [comment]
Thanks for reporting; should be fixed now.

**Comment by DeltaD36** [comment]
> Due to a github username change, the archive.json repository has stopped working
> It's still there, just hasn't been updated to reflect the name change as of yet and so it still points to the old URL. You can get it now at
> https://nstepien.github.io/archives.json/archives.json
> and update it directly in the script yourself

How exactly do I do this?

**Comment by kristian-94** [comment]
How do we fix this? I still get the error and I updated the add on

**Comment by ccd0** [comment]
Look at the archives tab of your settings and make sure the URL for auto-updates is set to
https://nstepien.github.io/archives.json/archives.json

**Comment by kristian-94** [comment]
@ccd0  ah perfect thank you so much! working now :+1:

**Comment by bakugo** [comment]
Just fyi, that repo is archived.

**Comment by kobuki** [comment]
```Error fetching archive data from
https://nstepien.github.io/archives.json/archives.json
Connection Error```

Error is back. Repo moved again?

**Comment by jimmyrustles** [comment]
Hey dudes, also have the same problem, tried this

> Look at the archives tab of your settings and make sure the URL for auto-updates is set to
https://nstepien.github.io/archives.json/archives.json

and still getting the same error.

**Comment by Micronetic** [comment]
Yep same problem here too.

**Comment by kobuki** [comment]
Fixed in #2808

**Comment by NaturalHarmonia** [comment]
The url is correct but I've been having this problem for several days now.
