### ISSUE TITLE
Posting doesn't seem to work with 4chan Pass

### ISSUE THREAD

**Issue by Airdemon2100** [ccd0/4chan-x#3122]
I can't seem the post with the 4chan pass is on. It could be an issue with the new captcha.

**Comment by saxamaphone69** [comment]
Does it happen when you disable 4chan X?

**Comment by Airdemon2100** [comment]
It works fine when 4chan X is disabled. When 4chan X is on, the submit button doesn't work in many threads when you have the 4chan pass activated.

**Comment by TidOS** [comment]
I'm not following the contributing guidelines but I am here to post a "me too"

**Comment by joaovitorbf** [comment]
Workaround:
Edit the script's setUsed function at line 23833 so it's like this:
`    setUsed: function() {
      if (d.cookie.indexOf('pass_enabled=1') >= 0) {
        return;
      }
      if (this.nodes.container) {
        return $.global(function() {
          return window.TCaptcha.clearChallenge();
        });
      }
    },`

**Comment by joaovitorbf** [comment]
Workaround:
Edit the script's setUsed function at line 23833 so it's like this:

```
    setUsed: function() {
      if (d.cookie.indexOf('pass_enabled=1') >= 0) {
        return;
      }
      if (this.nodes.container) {
        return $.global(function() {
          return window.TCaptcha.clearChallenge();
        });
      }
    },
```

**Comment by KingCorg** [comment]
Same here. The post "goes through" but it shows up in the thread, not attributed to me, and the QR box does not clear.

**Comment by joaovitorbf** [comment]
This issue has been fixed in the last update.
Open your user script manager and check for updates.

**Comment by Teapsalm** [comment]
Still doesn't work for me. Captcha is still being asked for to post.

**Comment by Silva4MM** [comment]
Over a year later, it is still not working. Not even in the beta.
