### ISSUE TITLE
Can anything be done about captchas?

### ISSUE THREAD

**Issue by Icarus77** [ccd0/4chan-x#407]
These captchas are getting out of hand now.  The ReCaptcha just shows nothing but image captchas that don't work 1/4 of the time, and the noscript captchas shows unreadable captchas witht he black blobs over the text most of the time.

Is there anything you know about or can do that can make the captchas for ReCaptcha at least go back to just being text?  Or to get the specific noscript captchas that were just one word long instead of the unreadable ones/  I remember there being some short update that changed/removed captchas for this a few months back, but I don't quite remember what it did.

**Comment by ccd0** [comment]
Google seems to be serving text captchas (with the checkbox step) if you change your User-Agent header to something it doesn't recognize, using something like https://addons.mozilla.org/en-us/firefox/addon/header-tool/.  And captchas tend to be easier if Google sees a referrer and Google login cookies.  But it's all subject to change whenever Google feels like breaking shit.  http://www.4chan.org/feedback is the right place to complain; the 4chan admins could easily bring the text captcha back.

**Comment by Icarus77** [comment]
I've installed the header tool, but I'm not sure what exactly to put into it because everything is blank, and I'm also not sure if I merely edit Google or some specific part of Google for the captchas only.

And is there nothing that you or I can do to make the noscript captchas not have the unreadable ones appear 90% of the time?  It seems like you get readable captchas with it for a few posts, but then it just sends infinite blob captchas after a certain limit.

**Comment by ccd0** [comment]
This works for me:

@^https?://www\.(google|gstatic)\.com/recaptcha/
User-Agent: kek

**Comment by Icarus77** [comment]
Seems to have changed it to the old worded captcha for now, thanks.  I'll refer any anons who complain about the image captchas to this.

**Comment by throwaway666** [comment]
piggybacking on this i'm having an issue where the captcha won't confirm. the box you click to get it to load the captcha or confirm you? it doesn't respond. i keep having to refresh pages to get it to work. i'll be able to make a post or two in a thread and then have to re-load the page because the box won't respond to clicks. i try clicking the "Captcha: 0" text to make it refresh the captcha window but it still remains bugged.

**Comment by ccd0** [comment]
@throwaway666

That's most likely an issue on Google's end, and not something I can fix.  See if you can reproduce it with the native extension and/or https://www.google.com/recaptcha/api2/demo.  You can try reporting it to https://groups.google.com/forum/#!forum/recaptcha.

**Comment by yuridump** [comment]
nocaptcha recaptcha's work fine for me until I queue multiple images in the quick reply and try to change the order. Then the box becomes unclickable.

**Comment by ccd0** [comment]
@yuridump
Oops, that is my fault.  I have the captcha disabled when you drag+drop things to prevent dropping files into the captcha, but it wasn't being re-enabled in that case.  Should be fixed now, thanks!

**Comment by throwaway666** [comment]
...it's not really something i can reproduce when it's only happening when i use 4chanx lol

**Comment by ccd0** [comment]
@throwaway666 
Have you seen it since v1.10.12.7?  That should have fixed it.

**Comment by MistahK** [comment]
I think I'm having the same issue as throwaway666. Maybe

I can't mouseclick the "I'm not a robot button" or any of the images if I've gone to another non-4chan tab and then gone back. Well, it'll work for 2 or 3 posts and then not allow me to click it. 

I have to refresh the tab to be able to use the mouse again. 

I can tab into the button and the images and hit enter on it but the mouse won't work on it.

I don't know how to test it since the native expansion forces the post successful page which then refreshes the page and the demo goes to a new page after working once successfully.

**Comment by MistahK** [comment]
I think I'm having the same issue as throwaway666. Maybe

I can't mouseclick the "I'm not a robot button" or any of the images if I've gone to another non-4chan tab and then gone back. Well, it'll work for 2 or 3 posts and then not allow me to click it. 

I have to refresh the tab to be able to use the mouse again. 

I can tab into the button and the images and hit enter on it but the mouse won't work on it.

I don't know how to test it since the native expansion forces the post successful page which then refreshes the page and the demo goes to a new page after working once successfully.

**Comment by ccd0** [comment]
@MistahK 
Was this on v1.10.12.6 or v1.10.12.7 and in what browser?

**Comment by MistahK** [comment]
Never mind, seems it was fixed. Apologies.

**Comment by ccd0** [comment]
@MistahK
It was, but do you have any idea what version you were running when you had the problem?  If you don't remember, no need to worry about it.

**Comment by deadman3000** [comment]
That header tool does nothing for me. I am still getting the image captchas which have become even more annoying with 'click all food' or 'click all drink'.

Is there nothing I can do but buy a 4chan pass?

**Comment by ccd0** [comment]
@deadman3000
Make sure you have it turned on.  There's a bug where it isn't enabled at startup.

**Comment by loadletter** [comment]
It seems like it reverts to image captchas once a text one is solved and cookies are set
If you don't use a google account you can either try disabling cookies for google.com or use something like:

```
@^https://www\.(google|gstatic)\.com/recaptcha/*
User-Agent: kek
Set-Cookie: lel
```

**Comment by ccd0** [comment]
@loadletter
That would explain it; I browse with third-party cookies blocked.

**Comment by ccd0** [comment]
@loadletter
Also I think you want `Cookie:`; `Set-Cookie` is a response header.

**Comment by loadletter** [comment]
Yes, my mistake.

**Comment by Icarus77** [comment]
@ccd0 
Do you know if there's a way to stop third party cookies for 4chan only?

**Comment by tenkuu** [comment]
Firefox:
1. Go to `about:permissions`
2. Find 4chan.org
3. Under `Set Cookies` select `Allow First Party Only`

**Comment by hotdogman** [comment]
rip
spoofing user agent no longer works
doing so gives burgercaptchas that cause the QR not to fit on screen
![screenshot104](https://cloud.githubusercontent.com/assets/4343306/8263583/d03f9c28-16a1-11e5-9a09-982f379ba28a.png)

**Comment by hotdogman** [comment]
rip
spoofing user agent no longer works
doing so gives burgercaptchas, which cause the QR not to fit on screen
another benefit is that the code can't be copy/pasted in to the box, and you have to start the captcha from scratch
![screenshot106](https://cloud.githubusercontent.com/assets/4343306/8263651/6773c07e-16a2-11e5-8c02-9190eaa9797b.png)
![screenshot107](https://cloud.githubusercontent.com/assets/4343306/8263650/6774618c-16a2-11e5-946e-86cc43db0ee7.png)
thanks google

**Comment by ccd0** [comment]
@hotdogman
I'm guessing the failure of the copy-paste captchas was due to 4chan X measuring their expiry time from the time the captcha was set up, and therefore immediately treating them as expired.  That should be fixed now.
